"""add extra_metadata to processus

Revision ID: 114d66248547
Revises: 813c144d0c30
Create Date: 2026-06-19 14:01:08.938654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114d66248547'
down_revision = '813c144d0c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fournisseur_partage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pays', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delai_livraison', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('taux_defaut', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_qualite', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_delai', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_prix', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_global', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commentaire_score', sa.Text(), nullable=True))

    with op.batch_alter_table('processus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('reclamation_partage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severite', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('categorie', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('investigation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cause_racine', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_corrective_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'action_corrective', ['action_corrective_id'], ['id'])

    with op.batch_alter_table('risque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processus_concerne', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plan_traitement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_preventive', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_corrective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_revu', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_prochaine_revu', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risque', schema=None) as batch_op:
        batch_op.drop_column('date_prochaine_revu')
        batch_op.drop_column('date_revu')
        batch_op.drop_column('action_corrective')
        batch_op.drop_column('action_preventive')
        batch_op.drop_column('plan_traitement')
        batch_op.drop_column('processus_concerne')
        batch_op.drop_column('categorie')

    with op.batch_alter_table('reclamation_partage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('action_corrective_id')
        batch_op.drop_column('cause_racine')
        batch_op.drop_column('investigation')
        batch_op.drop_column('categorie')
        batch_op.drop_column('severite')

    with op.batch_alter_table('processus', schema=None) as batch_op:
        batch_op.drop_column('extra_metadata')

    with op.batch_alter_table('fournisseur_partage', schema=None) as batch_op:
        batch_op.drop_column('commentaire_score')
        batch_op.drop_column('score_global')
        batch_op.drop_column('score_prix')
        batch_op.drop_column('score_delai')
        batch_op.drop_column('score_qualite')
        batch_op.drop_column('taux_defaut')
        batch_op.drop_column('delai_livraison')
        batch_op.drop_column('pays')

    # ### end Alembic commands ###
