"""create shared partage models (fournisseur, formation, reclamation)

Revision ID: 813c144d0c30
Revises: 6b39ac6ecd9a
Create Date: 2026-06-18 23:43:44.157039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '813c144d0c30'
down_revision = '6b39ac6ecd9a'
branch_labels = None
depends_on = None


def upgrade():
    # Drop old FK constraints before dropping old tables
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_fournisseur_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('evaluation_fournisseur', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('evaluation_fournisseur_fournisseur_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('formation_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('formation_participant_formation_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('historique_fournisseur', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historique_fournisseur_fournisseur_id_fkey'), type_='foreignkey')

    # Drop old tables now that FK constraints are removed
    op.drop_table('reclamation_client')
    op.drop_table('haccp_fournisseur')
    op.drop_table('haccp_reclamation')
    op.drop_table('formation')
    op.drop_table('fournisseur')
    op.drop_table('haccp_formation')

    # Create new FK constraints pointing to new tables
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fournisseur_partage', ['fournisseur_id'], ['id'])

    with op.batch_alter_table('evaluation_fournisseur', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fournisseur_partage', ['fournisseur_id'], ['id'])

    with op.batch_alter_table('formation_participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'formation_partage', ['formation_id'], ['id'])

    with op.batch_alter_table('historique_fournisseur', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fournisseur_partage', ['fournisseur_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historique_fournisseur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historique_fournisseur_fournisseur_id_fkey'), 'fournisseur', ['fournisseur_id'], ['id'])

    with op.batch_alter_table('formation_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('formation_participant_formation_id_fkey'), 'formation', ['formation_id'], ['id'])

    with op.batch_alter_table('evaluation_fournisseur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evaluation_fournisseur_fournisseur_id_fkey'), 'fournisseur', ['fournisseur_id'], ['id'])

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_fournisseur_id_fkey'), 'fournisseur', ['fournisseur_id'], ['id'])

    op.create_table('haccp_formation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('formateur', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('participants', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duree_heures', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_formation', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('evaluation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('haccp_formation_entreprise_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('haccp_formation_pkey'))
    )
    op.create_table('fournisseur',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('produit', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('evaluation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_qualification', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('certificats', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dernier_audit', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('fournisseur_entreprise_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fournisseur_pkey'))
    )
    op.create_table('formation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domaine', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('titre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('formateur', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('participants', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_formation', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('duree_heures', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('type_formation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('objectifs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prerequis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cout', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('annee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('formation_entreprise_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_pkey'))
    )
    op.create_table('haccp_reclamation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_reclamation', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('client', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('produit', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('lot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type_reclamation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responsable_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cloture_le', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('haccp_reclamation_entreprise_id_fkey')),
    sa.ForeignKeyConstraint(['responsable_id'], ['utilisateur.id'], name=op.f('haccp_reclamation_responsable_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('haccp_reclamation_pkey'))
    )
    op.create_table('haccp_fournisseur',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('produit_fourni', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('certification', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('evaluation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dernier_audit', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prochain_audit', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('haccp_fournisseur_entreprise_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('haccp_fournisseur_pkey'))
    )
    op.create_table('reclamation_client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_reclamation', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('client', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('produit', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('responsable_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('reclamation_client_entreprise_id_fkey')),
    sa.ForeignKeyConstraint(['responsable_id'], ['utilisateur.id'], name=op.f('reclamation_client_responsable_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reclamation_client_pkey'))
    )
    # ### end Alembic commands ###
