"""add employe_competence

Revision ID: a5a87cf11bea
Revises: c2d3e4f5g6a0
Create Date: 2026-06-19 22:32:21.948480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a87cf11bea'
down_revision = 'c2d3e4f5g6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_competence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('niveau_requis', sa.Integer(), nullable=True),
    sa.Column('niveau_actuel', sa.Integer(), nullable=True),
    sa.Column('date_evaluation', sa.Date(), nullable=True),
    sa.Column('evalue_par_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['evalue_par_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_competence')
    # ### end Alembic commands ###
