"""add 8 new module tables

Revision ID: eac3edf3f2d6
Revises: 114d66248547
Create Date: 2026-06-19 15:46:32.326568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac3edf3f2d6'
down_revision = '114d66248547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspect_environnemental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('gravite', sa.String(length=20), nullable=True),
    sa.Column('maitrise', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aspect_environnemental', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aspect_environnemental_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('employe_qhse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('poste', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('date_visite_medicale', sa.Date(), nullable=True),
    sa.Column('date_prochaine_visite', sa.Date(), nullable=True),
    sa.Column('habilitations', sa.JSON(), nullable=True),
    sa.Column('epi_attribues', sa.JSON(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employe_qhse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employe_qhse_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('equipement_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('localisation', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('date_acquisition', sa.Date(), nullable=True),
    sa.Column('date_derniere_maintenance', sa.Date(), nullable=True),
    sa.Column('date_prochaine_maintenance', sa.Date(), nullable=True),
    sa.Column('frequence_maintenance', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipement_maintenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipement_maintenance_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('evenement_planification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_evenement', sa.String(length=50), nullable=True),
    sa.Column('module_source', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('rappel_avant', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evenement_planification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evenement_planification_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('reponse', sa.Text(), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('vue_count', sa.Integer(), nullable=True),
    sa.Column('utile_count', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('main_courante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('date_evenement', sa.DateTime(), nullable=False),
    sa.Column('type_evenement', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('declares_par', sa.String(length=100), nullable=True),
    sa.Column('actions_entreprises', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('main_courante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_main_courante_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('plan_analyse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('produit_concerne', sa.String(length=200), nullable=True),
    sa.Column('parametre', sa.String(length=200), nullable=True),
    sa.Column('methode', sa.String(length=200), nullable=True),
    sa.Column('frequence', sa.String(length=100), nullable=True),
    sa.Column('seuil_min', sa.Float(), nullable=True),
    sa.Column('seuil_max', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_analyse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_analyse_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('plan_urgence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type_urgence', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('procedures', sa.Text(), nullable=True),
    sa.Column('contacts_cles', sa.JSON(), nullable=True),
    sa.Column('materiel', sa.Text(), nullable=True),
    sa.Column('date_derniere_revu', sa.Date(), nullable=True),
    sa.Column('date_prochaine_revu', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_urgence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_urgence_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('type_reunion', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_reunion', sa.DateTime(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('organisateur', sa.String(length=100), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reunion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reunion_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('rex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('contexte', sa.Text(), nullable=True),
    sa.Column('causes', sa.Text(), nullable=True),
    sa.Column('actions_menees', sa.Text(), nullable=True),
    sa.Column('resultats', sa.Text(), nullable=True),
    sa.Column('lecons_apprises', sa.Text(), nullable=True),
    sa.Column('auteur', sa.String(length=100), nullable=True),
    sa.Column('date_rex', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rex', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rex_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('action_reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reunion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_reunion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_reunion_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('compte_rendu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('ordre_du_jour', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('redige_par', sa.String(length=100), nullable=True),
    sa.Column('date_redaction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reunion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compte_rendu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compte_rendu_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('echantillon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('plan_analyse_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('produit', sa.String(length=200), nullable=True),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('date_prelevement', sa.DateTime(), nullable=True),
    sa.Column('preleve_par', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['plan_analyse_id'], ['plan_analyse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('echantillon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_echantillon_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('exercice_evacuation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('plan_urgence_id', sa.Integer(), nullable=True),
    sa.Column('date_exercice', sa.DateTime(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('resultat', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('ameliorations', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['plan_urgence_id'], ['plan_urgence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercice_evacuation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercice_evacuation_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('intervention_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=False),
    sa.Column('type_intervention', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('cout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pieces_rechange', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipement_maintenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intervention_maintenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intervention_maintenance_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('suivi_environnemental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('aspect_id', sa.Integer(), nullable=True),
    sa.Column('type_suivi', sa.String(length=50), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('periode', sa.String(length=20), nullable=True),
    sa.Column('date_mesure', sa.Date(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect_environnemental.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suivi_environnemental', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suivi_environnemental_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('resultat_analyse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('echantillon_id', sa.Integer(), nullable=False),
    sa.Column('parametre', sa.String(length=200), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('conforme', sa.Boolean(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('analyse_par', sa.String(length=100), nullable=True),
    sa.Column('date_analyse', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['echantillon_id'], ['echantillon.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultat_analyse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultat_analyse_entreprise_id'), ['entreprise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultat_analyse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultat_analyse_entreprise_id'))

    op.drop_table('resultat_analyse')
    with op.batch_alter_table('suivi_environnemental', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suivi_environnemental_entreprise_id'))

    op.drop_table('suivi_environnemental')
    with op.batch_alter_table('intervention_maintenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intervention_maintenance_entreprise_id'))

    op.drop_table('intervention_maintenance')
    with op.batch_alter_table('exercice_evacuation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercice_evacuation_entreprise_id'))

    op.drop_table('exercice_evacuation')
    with op.batch_alter_table('echantillon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_echantillon_entreprise_id'))

    op.drop_table('echantillon')
    with op.batch_alter_table('compte_rendu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compte_rendu_entreprise_id'))

    op.drop_table('compte_rendu')
    with op.batch_alter_table('action_reunion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_reunion_entreprise_id'))

    op.drop_table('action_reunion')
    with op.batch_alter_table('rex', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rex_entreprise_id'))

    op.drop_table('rex')
    with op.batch_alter_table('reunion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reunion_entreprise_id'))

    op.drop_table('reunion')
    with op.batch_alter_table('plan_urgence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_urgence_entreprise_id'))

    op.drop_table('plan_urgence')
    with op.batch_alter_table('plan_analyse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_analyse_entreprise_id'))

    op.drop_table('plan_analyse')
    with op.batch_alter_table('main_courante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_courante_entreprise_id'))

    op.drop_table('main_courante')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_entreprise_id'))

    op.drop_table('faq')
    with op.batch_alter_table('evenement_planification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evenement_planification_entreprise_id'))

    op.drop_table('evenement_planification')
    with op.batch_alter_table('equipement_maintenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipement_maintenance_entreprise_id'))

    op.drop_table('equipement_maintenance')
    with op.batch_alter_table('employe_qhse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employe_qhse_entreprise_id'))

    op.drop_table('employe_qhse')
    with op.batch_alter_table('aspect_environnemental', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aspect_environnemental_entreprise_id'))

    op.drop_table('aspect_environnemental')
    # ### end Alembic commands ###
